safe:   false

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

permalink:   /:title

paginate: 5

future: false

prod_url: http://blog.wildtrip.net

flickr:
  cache_dir:        ./_cache/flickr
  api_key:          xx
  shared_secret:    xx
  access_token:     xx-xx
  access_secret:    xx

tag_dir: tag
tag_title_prefix: 'Billets étiquetés &ldquo;'
tag_title_suffix: '&rdquo;'

algolia:
  index_name: blog_posts
  application_id: xx
  search_only_api_key: xx

tag_location:
  chine: "[104.195397, 35.861660]"
  hongkong: "[114.109497, 22.396428]"
  coreedusud: "[127.766922, 35.907757]"
  indonesie: "[113.921327, -0.789275]"
  thailande: "[99.711914, 13.496473]"
  malaisie: "[101.975766, 4.210484]"
  france: "[2.213749, 46.227638]"
  ukraine: "[30.794678, 49.337204]"
  russie: "[62.132492, 56.628924]"
  mongolie: "[106.907272, 47.921720]"

#
# Plugin: jekyll-assets
#
assets:
  #
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  #
  dirname: assets
  #
  # Base URL of assets paths.
  #
  baseurl: /assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/js
    - _assets/css
    # - _assets/img
  #
  # Sets JS compressor. No compression by default.
  # Possible variants: 'yui', 'uglifier', nil
  #
  js_compressor: uglifier
  #
  # Sets CSS compressor. No compression by default.
  # Possible variants: 'yui', 'sass', nil
  #
  css_compressor: sass
  #
  # Sets cachebusting policy for generated assets.
  #
  # Possible variants:
  #
  #   none - disables cachebusting
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css
  #
  #   soft - leave filenames as-is, but `?cb=<md5>` suffix for URLs generated
  #          with `asset_path`, `javascript` and `stylesheet`:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css?cb=4f41243847da693a4f356c0486114bc6
  #
  #   hard - (default) injects cachebusting checksum into processed filename:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app-4f41243847da693a4f356c0486114bc6.css
  #     output URL:   /assets/javascripts/app-4f41243847da693a4f356c0486114bc6.css
  #
  cachebust: hard
  #
  # Whenever or not cache compiled assets (disabled by default).
  # See `Compilation Cache` section of README for details.
  #
  cache: false
  #
  # Specifies list of MIME types that needs to have gzipped versions.
  # You can set it to `false` to disable gzipping. Only javascripts and
  # stylesheets are gzipped by default.
  #
  gzip: [ text/css, application/javascript ]
  #
  # Does not concatenates files requested by `javascript` and `stylesheet`
  # helpers. Instead outputs multiple files in order they are required.
  # Default: false
  #
  debug: false
