(function(e,t,u,v){var p=function(){},z=function(d,a){if(d.hasClass(a.slides_container_class))return this;var c=this,f,m,g,k,h=0,n,l;c.slides=function(){return d.children(a.slide_selector)};c.slides().first().addClass(a.active_slide_class);c.update_slide_number=function(b){a.slide_number&&(m.find("span:first").text(parseInt(b)+1),m.find("span:last").text(c.slides().length));a.bullets&&(g.children().removeClass(a.bullets_active_class),e(g.children().get(b)).addClass(a.bullets_active_class))};c.update_active_link=
function(b){b=e('[data-orbit-link="'+c.slides().eq(b).attr("data-orbit-slide")+'"]');b.siblings().removeClass(a.bullets_active_class);b.addClass(a.bullets_active_class)};c.build_markup=function(){d.wrap('<div class="'+a.container_class+'"></div>');f=d.parent();d.addClass(a.slides_container_class);a.stack_on_small&&f.addClass(a.stack_on_small_class);a.navigation_arrows&&(f.append(e('<a href="#"><span></span></a>').addClass(a.prev_class)),f.append(e('<a href="#"><span></span></a>').addClass(a.next_class)));
a.timer&&(k=e("<div>").addClass(a.timer_container_class),k.append("<span>"),k.append(e("<div>").addClass(a.timer_progress_class)),k.addClass(a.timer_paused_class),f.append(k));a.slide_number&&(m=e("<div>").addClass(a.slide_number_class),m.append("<span></span> "+a.slide_number_text+" <span></span>"),f.append(m));a.bullets&&(g=e("<ol>").addClass(a.bullets_container_class),f.append(g),g.wrap('<div class="orbit-bullets-container"></div>'),c.slides().each(function(b,a){var d=e("<li>").attr("data-orbit-slide",
b).on("click",c.link_bullet);g.append(d)}))};c._goto=function(b,f){if(b===h)return!1;"object"===typeof l&&l.restart();var g=c.slides(),m="next";b<h&&(m="prev");if(b>=g.length){if(!a.circular)return!1;b=0}else if(0>b){if(!a.circular)return!1;b=g.length-1}var q=e(g.get(h)),k=e(g.get(b));q.css("zIndex",2);q.removeClass(a.active_slide_class);k.css("zIndex",4).addClass(a.active_slide_class);d.trigger("before-slide-change.fndtn.orbit");a.before_slide_change();c.update_active_link(b);var r=function(){var e=
function(){h=b;!0===f&&(l=c.create_timer(),l.start());c.update_slide_number(h);d.trigger("after-slide-change.fndtn.orbit",[{slide_number:h,total_slides:g.length}]);a.after_slide_change(h,g.length)};d.outerHeight()!=k.outerHeight()&&a.variable_height?d.animate({height:k.outerHeight()},250,"linear",e):e()};if(1===g.length)return r(),!1;var p=function(){"next"===m&&n.next(q,k,r);"prev"===m&&n.prev(q,k,r)};k.outerHeight()>d.outerHeight()&&a.variable_height?d.animate({height:k.outerHeight()},250,"linear",
p):p()};c.next=function(b){b.stopImmediatePropagation();b.preventDefault();c._goto(h+1)};c.prev=function(b){b.stopImmediatePropagation();b.preventDefault();c._goto(h-1)};c.link_custom=function(b){b.preventDefault();b=e(this).attr("data-orbit-link");"string"===typeof b&&""!=(b=e.trim(b))&&(b=f.find("[data-orbit-slide="+b+"]"),-1!=b.index()&&c._goto(b.index()))};c.link_bullet=function(b){b=e(this).attr("data-orbit-slide");"string"===typeof b&&""!=(b=e.trim(b))&&(isNaN(parseInt(b))?(b=f.find("[data-orbit-slide="+
b+"]"),-1!=b.index()&&c._goto(b.index()+1)):c._goto(parseInt(b)))};c.timer_callback=function(){c._goto(h+1,!0)};c.compute_dimensions=function(){var b=e(c.slides().get(h)).outerHeight();a.variable_height||c.slides().each(function(){e(this).outerHeight()>b&&(b=e(this).outerHeight())});d.height(b)};c.create_timer=function(){return new w(f.find("."+a.timer_container_class),a,c.timer_callback)};c.stop_timer=function(){"object"===typeof l&&l.stop()};c.toggle_timer=function(){f.find("."+a.timer_container_class).hasClass(a.timer_paused_class)?
("undefined"===typeof l&&(l=c.create_timer()),l.start()):"object"===typeof l&&l.stop()};c.init=function(){c.build_markup();a.timer&&(l=c.create_timer(),Foundation.utils.image_loaded(this.slides().children("img"),l.start));n=new x(a,d);"slide"===a.animation&&(n=new y(a,d));f.on("click","."+a.next_class,c.next);f.on("click","."+a.prev_class,c.prev);if(a.next_on_click)f.on("click","."+a.slides_container_class+" [data-orbit-slide]",c.link_bullet);f.on("click",c.toggle_timer);if(a.swipe)f.on("touchstart.fndtn.orbit",
function(b){b.touches||(b=b.originalEvent);var a={start_page_x:b.touches[0].pageX,start_page_y:b.touches[0].pageY,start_time:(new Date).getTime(),delta_x:0,is_scrolling:v};f.data("swipe-transition",a);b.stopPropagation()}).on("touchmove.fndtn.orbit",function(b){b.touches||(b=b.originalEvent);if(!(1<b.touches.length||b.scale&&1!==b.scale)){var a=f.data("swipe-transition");"undefined"===typeof a&&(a={});a.delta_x=b.touches[0].pageX-a.start_page_x;"undefined"===typeof a.is_scrolling&&(a.is_scrolling=
!!(a.is_scrolling||Math.abs(a.delta_x)<Math.abs(b.touches[0].pageY-a.start_page_y)));a.is_scrolling||a.active||(b.preventDefault(),b=0>a.delta_x?h+1:h-1,a.active=!0,c._goto(b))}}).on("touchend.fndtn.orbit",function(a){f.data("swipe-transition",{});a.stopPropagation()});f.on("mouseenter.fndtn.orbit",function(b){a.timer&&a.pause_on_hover&&c.stop_timer()}).on("mouseleave.fndtn.orbit",function(b){a.timer&&a.resume_on_mouseout&&l.start()});e(u).on("click","[data-orbit-link]",c.link_custom);e(t).on("load resize",
c.compute_dimensions);Foundation.utils.image_loaded(this.slides().children("img"),c.compute_dimensions);Foundation.utils.image_loaded(this.slides().children("img"),function(){f.prev("."+a.preloader_class).css("display","none");c.update_slide_number(0);c.update_active_link(0);d.trigger("ready.fndtn.orbit")})};c.init()},w=function(d,a,c){var f=this,e=a.timer_speed,g=d.find("."+a.timer_progress_class),k,h,n=-1;this.update_progress=function(a){var b=g.clone();b.attr("style","");b.css("width",a+"%");g.replaceWith(b);
g=b};this.restart=function(){clearTimeout(h);d.addClass(a.timer_paused_class);n=-1;f.update_progress(0)};this.start=function(){if(!d.hasClass(a.timer_paused_class))return!0;n=-1===n?e:n;d.removeClass(a.timer_paused_class);k=(new Date).getTime();g.animate({width:"100%"},n,"linear");h=setTimeout(function(){f.restart();c()},n);d.trigger("timer-started.fndtn.orbit")};this.stop=function(){if(d.hasClass(a.timer_paused_class))return!0;clearTimeout(h);d.addClass(a.timer_paused_class);var c=(new Date).getTime();
n-=c-k;f.update_progress(100-n/e*100);d.trigger("timer-stopped.fndtn.orbit")}},y=function(d,a){var c=d.animation_speed,f=1===e("html[dir=rtl]").length?"marginRight":"marginLeft",m={};m[f]="0%";this.next=function(a,d,e){a.animate({marginLeft:"-100%"},c);d.animate(m,c,function(){a.css(f,"100%");e()})};this.prev=function(a,d,e){a.animate({marginLeft:"100%"},c);d.css(f,"-100%");d.animate(m,c,function(){a.css(f,"100%");e()})}},x=function(d,a){var c=d.animation_speed;e("html[dir=rtl]");this.next=function(a,
d,e){d.css({margin:"0%",opacity:"0.01"});d.animate({opacity:"1"},c,"linear",function(){a.css("margin","100%");e()})};this.prev=function(a,d,e){d.css({margin:"0%",opacity:"0.01"});d.animate({opacity:"1"},c,"linear",function(){a.css("margin","100%");e()})}};Foundation.libs=Foundation.libs||{};Foundation.libs.orbit={name:"orbit",version:"5.5.3",settings:{animation:"slide",timer_speed:1E4,pause_on_hover:!0,resume_on_mouseout:!1,next_on_click:!0,animation_speed:500,stack_on_small:!1,navigation_arrows:!0,
slide_number:!0,slide_number_text:"of",container_class:"orbit-container",stack_on_small_class:"orbit-stack-on-small",next_class:"orbit-next",prev_class:"orbit-prev",timer_container_class:"orbit-timer",timer_paused_class:"paused",timer_progress_class:"orbit-progress",slides_container_class:"orbit-slides-container",preloader_class:"preloader",slide_selector:"*",bullets_container_class:"orbit-bullets",bullets_active_class:"active",slide_number_class:"orbit-slide-number",caption_class:"orbit-caption",
active_slide_class:"active",orbit_transition_class:"orbit-transitioning",bullets:!0,circular:!0,timer:!0,variable_height:!1,swipe:!0,before_slide_change:p,after_slide_change:p},init:function(d,a,c){this.bindings(a,c)},events:function(d){var a=new z(this.S(d),this.S(d).data("orbit-init"));this.S(d).data(this.name+"-instance",a)},reflow:function(){var d=this;d.S(d.scope).is("[data-orbit]")?d.S(d.scope).data(d.name+"-instance").compute_dimensions():d.S("[data-orbit]",d.scope).each(function(a,c){var e=
d.S(c);d.data_options(e);e.data(d.name+"-instance").compute_dimensions()})}}})(jQuery,window,window.document);
