(function(e,h,l,m){Foundation.libs.topbar={name:"topbar",version:"5.5.3",settings:{index:0,start_offset:0,sticky_class:"sticky",custom_back_text:!0,back_text:"Back",mobile_show_parent_link:!0,is_hover:!0,scrolltop:!0,sticky_on:"all",dropdown_autoclose:!0},init:function(a,b,d){Foundation.inherit(this,"add_custom_rule register_media throttle");var c=this;c.register_media("topbar","foundation-mq-topbar");this.bindings(b,d);c.S("["+this.attr_name()+"]",this.scope).each(function(){var a=e(this),b=a.data(c.attr_name(!0)+
"-init");c.S("section, .top-bar-section",this);a.data("index",0);var d=a.parent();d.hasClass("fixed")||c.is_sticky(a,d,b)?(c.settings.sticky_class=b.sticky_class,c.settings.sticky_topbar=a,a.data("height",d.outerHeight()),a.data("stickyoffset",d.offset().top)):a.data("height",a.outerHeight());b.assembled||c.assemble(a);b.is_hover?c.S(".has-dropdown",a).addClass("not-click"):c.S(".has-dropdown",a).removeClass("not-click");c.add_custom_rule(".f-topbar-fixed { padding-top: "+a.data("height")+"px }");
d.hasClass("fixed")&&c.S("body").addClass("f-topbar-fixed")})},is_sticky:function(a,b,d){a=b.hasClass(d.sticky_class);b=matchMedia(Foundation.media_queries.small).matches;var c=matchMedia(Foundation.media_queries.medium).matches,k=matchMedia(Foundation.media_queries.large).matches;return a&&"all"===d.sticky_on||a&&this.small()&&-1!==d.sticky_on.indexOf("small")&&b&&!c&&!k||a&&this.medium()&&-1!==d.sticky_on.indexOf("medium")&&b&&c&&!k||a&&this.large()&&-1!==d.sticky_on.indexOf("large")&&b&&c&&k?!0:
!1},toggle:function(a){a=a?this.S(a).closest("["+this.attr_name()+"]"):this.S("["+this.attr_name()+"]");var b=a.data(this.attr_name(!0)+"-init"),d=this.S("section, .top-bar-section",a);this.breakpoint()&&(this.rtl?(d.css({right:"0%"}),e(">.name",d).css({right:"100%"})):(d.css({left:"0%"}),e(">.name",d).css({left:"100%"})),this.S("li.moved",d).removeClass("moved"),a.data("index",0),a.toggleClass("expanded").css("height",""));b.scrolltop?a.hasClass("expanded")?a.parent().hasClass("fixed")&&(b.scrolltop?
(a.parent().removeClass("fixed"),a.addClass("fixed"),this.S("body").removeClass("f-topbar-fixed"),h.scrollTo(0,0)):a.parent().removeClass("expanded")):a.hasClass("fixed")&&(a.parent().addClass("fixed"),a.removeClass("fixed"),this.S("body").addClass("f-topbar-fixed")):(this.is_sticky(a,a.parent(),b)&&a.parent().addClass("fixed"),a.parent().hasClass("fixed")&&(a.hasClass("expanded")?(a.addClass("fixed"),a.parent().addClass("expanded"),this.S("body").addClass("f-topbar-fixed")):(a.removeClass("fixed"),
a.parent().removeClass("expanded"),this.update_sticky_positioning())))},timer:null,events:function(a){var b=this,d=this.S;d(this.scope).off(".topbar").on("click.fndtn.topbar","["+this.attr_name()+"] .toggle-topbar",function(a){a.preventDefault();b.toggle(this)}).on("click.fndtn.topbar contextmenu.fndtn.topbar",'.top-bar .top-bar-section li a[href^="#"],['+this.attr_name()+'] .top-bar-section li a[href^="#"]',function(a){a=e(this).closest("li");var c=a.closest("["+b.attr_name()+"]").data(b.attr_name(!0)+
"-init");c.dropdown_autoclose&&c.is_hover&&e(this).closest(".hover").removeClass("hover");!b.breakpoint()||a.hasClass("back")||a.hasClass("has-dropdown")||b.toggle()}).on("click.fndtn.topbar","["+this.attr_name()+"] li.has-dropdown",function(a){var c=d(this),g=d(a.target),f=c.closest("["+b.attr_name()+"]").data(b.attr_name(!0)+"-init");g.data("revealId")?b.toggle():b.breakpoint()||f.is_hover&&!Modernizr.touch||(a.stopImmediatePropagation(),c.hasClass("hover")?(c.removeClass("hover").find("li").removeClass("hover"),
c.parents("li.hover").removeClass("hover")):(c.addClass("hover"),e(c).siblings().removeClass("hover"),"A"===g[0].nodeName&&g.parent().hasClass("has-dropdown")&&a.preventDefault()))}).on("click.fndtn.topbar","["+this.attr_name()+"] .has-dropdown>a",function(a){if(b.breakpoint()){a.preventDefault();a=d(this);var c=a.closest("["+b.attr_name()+"]"),g=c.find("section, .top-bar-section");a.next(".dropdown").outerHeight();var e=a.closest("li");c.data("index",c.data("index")+1);e.addClass("moved");b.rtl?
(g.css({right:-(100*c.data("index"))+"%"}),g.find(">.name").css({right:100*c.data("index")+"%"})):(g.css({left:-(100*c.data("index"))+"%"}),g.find(">.name").css({left:100*c.data("index")+"%"}));c.css("height",a.siblings("ul").outerHeight(!0)+c.data("height"))}});d(h).off(".topbar").on("resize.fndtn.topbar",b.throttle(function(){b.resize.call(b)},50)).trigger("resize.fndtn.topbar").load(function(){d(this).trigger("resize.fndtn.topbar")});d("body").off(".topbar").on("click.fndtn.topbar",function(a){0<
d(a.target).closest("li").closest("li.hover").length||d("["+b.attr_name()+"] li.hover").removeClass("hover")});d(this.scope).on("click.fndtn.topbar","["+this.attr_name()+"] .has-dropdown .back",function(a){a.preventDefault();var c=d(this);a=c.closest("["+b.attr_name()+"]");var e=a.find("section, .top-bar-section");a.data(b.attr_name(!0)+"-init");var f=c.closest("li.moved"),c=f.parent();a.data("index",a.data("index")-1);b.rtl?(e.css({right:-(100*a.data("index"))+"%"}),e.find(">.name").css({right:100*
a.data("index")+"%"})):(e.css({left:-(100*a.data("index"))+"%"}),e.find(">.name").css({left:100*a.data("index")+"%"}));0===a.data("index")?a.css("height",""):a.css("height",c.outerHeight(!0)+a.data("height"));setTimeout(function(){f.removeClass("moved")},300)});d(this.scope).find(".dropdown a").focus(function(){e(this).parents(".has-dropdown").addClass("hover")}).blur(function(){e(this).parents(".has-dropdown").removeClass("hover")})},resize:function(){var a=this;a.S("["+this.attr_name()+"]").each(function(){var b=
a.S(this),d=b.data(a.attr_name(!0)+"-init"),c=b.parent("."+a.settings.sticky_class);if(!a.breakpoint()){var e=b.hasClass("expanded");b.css("height","").removeClass("expanded").find("li").removeClass("hover");e&&a.toggle(b)}a.is_sticky(b,c,d)&&(c.hasClass("fixed")?(c.removeClass("fixed"),d=c.offset().top,a.S(l.body).hasClass("f-topbar-fixed")&&(d-=b.data("height")),b.data("stickyoffset",d),c.addClass("fixed")):(d=c.offset().top,b.data("stickyoffset",d)))})},breakpoint:function(){return!matchMedia(Foundation.media_queries.topbar).matches},
small:function(){return matchMedia(Foundation.media_queries.small).matches},medium:function(){return matchMedia(Foundation.media_queries.medium).matches},large:function(){return matchMedia(Foundation.media_queries.large).matches},assemble:function(a){var b=this,d=a.data(this.attr_name(!0)+"-init"),c=b.S("section, .top-bar-section",a);c.detach();b.S(".has-dropdown>a",c).each(function(){var a=b.S(this),c=a.siblings(".dropdown"),f=a.attr("href");c.find(".title.back").length||(f=1==d.mobile_show_parent_link&&
f?e('<li class="title back js-generated"><h5><a href="javascript:void(0)"></a></h5></li><li class="parent-link hide-for-medium-up"><a class="parent-link js-generated" href="'+f+'">'+a.html()+"</a></li>"):e('<li class="title back js-generated"><h5><a href="javascript:void(0)"></a></h5>'),1==d.custom_back_text?e("h5>a",f).html(d.back_text):e("h5>a",f).html("&laquo; "+a.html()),c.prepend(f))});c.appendTo(a);this.sticky();this.assembled(a)},assembled:function(a){a.data(this.attr_name(!0),e.extend({},
a.data(this.attr_name(!0)),{assembled:!0}))},height:function(a){var b=0,d=this;e("> li",a).each(function(){b+=d.S(this).outerHeight(!0)});return b},sticky:function(){var a=this;this.S(h).on("scroll",function(){a.update_sticky_positioning()})},update_sticky_positioning:function(){var a="."+this.settings.sticky_class,b=this.S(h);if(this.settings.sticky_topbar&&this.is_sticky(this.settings.sticky_topbar,this.settings.sticky_topbar.parent(),this.settings)){var d=this.settings.sticky_topbar.data("stickyoffset")+
this.settings.start_offset;this.S(a).hasClass("expanded")||(b.scrollTop()>d?this.S(a).hasClass("fixed")||(this.S(a).addClass("fixed"),this.S("body").addClass("f-topbar-fixed")):b.scrollTop()<=d&&this.S(a).hasClass("fixed")&&(this.S(a).removeClass("fixed"),this.S("body").removeClass("f-topbar-fixed")))}},off:function(){this.S(this.scope).off(".fndtn.topbar");this.S(h).off(".fndtn.topbar")},reflow:function(){}}})(jQuery,window,window.document);
